### PR TITLE
fix: Diagnostics are out of sync

### LINKED ISSUE #692: Diagnostics are out of sync
The LSP4MP diagnostics info seems to lag behind the user changes, showing diagnostic info from a previous state of the document before the change.
Here, a Bulkhead value of `-1` does get underlined in red, but there is no hover info: 
image

Adding a second digit, the diagnostic info updates to show the previous error:
image

When quickly entering a few more characters, a seemingly random number of changes get processed in the diagnostic update, but never seems to be fully up-to-date with the changes. In both the following cases, I started with `-12` and quickly added `1234` in one quick stroke.
image
image

When I highlight the entire value and fix it to something appropriate, the diagnostic for the old value still remains, while also keeping the red underline for the same number of characters in the previous error (you can see it extend to part of `public` a couple lines down):
image

Environment info: 
Quarkus tools: 1.14.0.292
IntelliJ 2022.2.3
OS: Reproduced on both macOS 13.0.1 and Windows 10
Plugins downloaded: 
image

### PR DESCRIPTION
**Pull request by angelozerr**
fix: Diagnostics are out of sync

Fixes #692

### CODE REVIEW

**Review by adietish — APPROVED** [review]
tested it with an annotation `Timeout(1000)` that I set it to an invalid negative value `Timeout(-1000)` and then back again. Validation worked correctly, indicated an invalid value and became valid again once the value was back to positive.

**Comment by angelozerr** [comment]
> tested it with an annotation Timeout(1000) that I set it to an invalid negative value Timeout(-1000) and then back again. Validation worked correctly, indicated an invalid value and became valid again once the value was back to positive.

Nice! Thanks for having tested that.

And what about code action issue https://github.com/redhat-developer/intellij-quarkus/issues/799 ?

It should work better without blocking the validation process.

**Comment by angelozerr** [comment]
Thanks so much @adietish for your review.

**Comment by adietish** [comment]
@angelozerr:

> And what about code action issue #799 ?
> 
> It should work better without blocking the validation process.

didn't measure but it felt like there was less time needed before the suggestion was offered again (after undo of the initial insertion).

**Comment by angelozerr** [comment]
> didn't measure but it felt like there was less time needed before the suggestion was offered again (after undo of the initial insertion).

Nice! I have another ideas how to improve again this problem.

**Comment by angelozerr** [comment]
I think https://github.com/redhat-developer/intellij-quarkus/pull/809 should  improve again performance code action, please give me feedback.

File: src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+
+    private static void updateAnnotations(List<Annotation> existingAnnotations, AnnotationHolder holder) {
+        if (existingAnnotations == null || existingAnnotations.isEmpty()) {
+            return;
+        }
+        // Copy all existing annotations in the given annotation holder.
+        existingAnnotations.forEach(currentAnnotation -> {
+            // Copy range, severity, message information
+            TextRange range = new TextRange(currentAnnotation.getStartOffset() , currentAnnotation.getEndOffset());
+            Annotation newAnnotation = holder.createAnnotation(currentAnnotation.getSeverity(),  range, currentAnnotation.getMessage());
```
Comment (evie-lau) [inline src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java:108]: @angelozerr I tried mirroring these changes in liberty-tools-intellij. I'm getting this Exception whenever an annotation is getting created.
```
Caused by: com.intellij.util.IncorrectOperationException: 'AnnotationHolder.createAnnotation()' method (the call to which was found in class io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.diagnostics.LSPDiagnosticAnnotator) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation(...).create()` instead
```
I am running on IntelliJ 2023.1 with intellij gradle plugin 1.13.3, so possibly it is just deprecated in some of these newer versions.

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java:108]: Ok thanks for your feedback. You mean that it doesn't work or it is just a warning message?

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java:108]: I hav enot used this create method because it doesn't return the Annotation and I need to store it to update quick fix in async mode. I need to investigate more how to use create method.

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java:108]: OK thanks for your feedback. I have investigate how to use the non deprecated api with annotation and I have found a solution. 

I will ping you when I will create the PR

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java:108]: @evie-lau please see https://github.com/redhat-developer/intellij-quarkus/pull/819
