### PR TITLE
fix: fix unit test and integration test

### LINKED ISSUE #1343: After creation project is not fully recognized as Maven project
I use the IntelliJ Ultimate and have disabled the bundled Quarkus plugin

image

Then, I create a new Quarkus project.

As you can see in the screenshot below, the Maven icon is missing:

image

I also cannot activate it from the menu:

image

This means the project is not fully recognized as Maven project, for some reason.

If I reopen the project, the Maven icon will appear.

### LINKED ISSUE #1435: Fix Tests after migrating to intellij gradle 2.x
- fix unit test failure
- fix integration tests failures

### PR DESCRIPTION
**Pull request by sbouchet**
fixes #1435 
fixes #1343

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusDeploymentSupport.java [hunk 1]
```diff
@@ -148,14 +148,12 @@ private synchronized static CompletableFuture<Void> internalUpdateClasspathWithQ
         }
         var project = module.getProject();
         final CompletableFuture<Void> future = new CompletableFuture<>();
-        CompletableFuture.runAsync(() -> {
-            Runnable task = () -> ProgressManager.getInstance().run(new Task.Backgroundable(project, "Adding Quarkus deployment dependencies to classpath...") {
+        MavenUtil.invokeAndWait(project, () -> ProgressManager.getInstance().run(new Task.Backgroundable(project, "Adding Quarkus deployment dependencies to classpath...") {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusDeploymentSupport.java:151]: Your code seems blocking the Thread 'since you are using invokeAndWait. The current code uses runAsynch.

Comment (sbouchet) [reply src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusDeploymentSupport.java]: reverted this change.

**Comment by angelozerr** [comment]
LGTM.

Thanks @sbouchet !
