### PR TITLE
fix: synchronize LSP console trace level with settings page

### LINKED ISSUE #1062: Message levels in LSP Consoles view not updated if changed from the settings pages
Set the message levels to `verbose` in the LSP Consoles view, then set them to `off` from the Language Servers preferences page, the levels in the console view still show as `verbose`.
The LSP consoles view should use a preference listener to update automatically.

### PR DESCRIPTION
**Pull request by fbricon**
Fixes #1062

Aug-10-2023 12-47-54

Since the settings are opened in a modal window, no need to synchronize console view changes -> settings page

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java [hunk 1]
```diff
@@ -139,10 +141,14 @@ private class ConsoleContentPanel extends SimpleCardLayoutPanel<JComponent> {
 
         private ConsoleView consoleView;
 
+        private Set<Runnable> settingsChangeListeners = new HashSet<>();
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java:144]: private final

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java [hunk 2]
```diff
@@ -139,10 +141,14 @@ private class ConsoleContentPanel extends SimpleCardLayoutPanel<JComponent> {
 
         private ConsoleView consoleView;
 
+        private Set<Runnable> settingsChangeListeners = new HashSet<>();
+
         public ConsoleContentPanel(DefaultMutableTreeNode key) {
             if (key instanceof LanguageServerTreeNode) {
                 add(createDetailPanel((LanguageServerTreeNode) key), NAME_VIEW_DETAIL);
                 showDetail();
+
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java:150]: remove those blank lines

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java [hunk 3]
```diff
@@ -224,6 +252,9 @@ public void showError(Throwable exception) {
 
         @Override
         public void dispose() {
+            for (Runnable settingsChangeListener : settingsChangeListeners) {
+                UserDefinedLanguageServerSettings.getInstance(getProject()).removeChangeHandler(settingsChangeListener);
+            }
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/console/LSPConsoleToolWindowPanel.java:257]: settingsChangeListener.clear();

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/settings/UserDefinedLanguageServerSettings.java [hunk 4]
```diff
@@ -108,4 +114,18 @@ public static class MyState {
 
     }
 
+    public void addChangeHandler(Runnable runnable) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/settings/UserDefinedLanguageServerSettings.java:117]: Add javadoc

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/settings/UserDefinedLanguageServerSettings.java [hunk 5]
```diff
@@ -108,4 +114,18 @@ public static class MyState {
 
     }
 
+    public void addChangeHandler(Runnable runnable) {
+        myChangeHandlers.add(runnable);
+    }
+
+    public void removeChangeHandler(Runnable runnable) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/settings/UserDefinedLanguageServerSettings.java:121]: Add javadoc

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/settings/UserDefinedLanguageServerSettings.java [hunk 6]
```diff
@@ -108,4 +114,18 @@ public static class MyState {
...
 
+    public void addChangeHandler(Runnable runnable) {
+        myChangeHandlers.add(runnable);
+    }
+
+    public void removeChangeHandler(Runnable runnable) {
+        myChangeHandlers.remove(runnable);
+    }
+
+    public void fireStateChanged() {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/settings/UserDefinedLanguageServerSettings.java:125]: Add javadoc

**Comment by angelozerr** [comment]
It weks very well. Thanks @fbricon !
