### PR TITLE
fix: Removed the Unused method TextEditConverter.convertToTextDocumentEdit(int)

### LINKED ISSUE #1425: Address usage of deprecated constructor 'VersionedTextDocumentIdentifier.<init>(Integer)'
The method `TextEditConverter.convertToTextDocumentEdit(int)` invokes the deprecated constructor `VersionedTextDocumentIdentifier.(Integer)`. 
Since the method has no usages, it should be removed.

### PR DESCRIPTION
**Pull request by anusreelakshmi934**
Fixes #1425

### CODE REVIEW

**Comment by anusreelakshmi934** [comment]
@angelozerr, kindly review this PR at your convenience. Thanks

**Comment by angelozerr** [comment]
I will keep this method and I will consume it here:

https://github.com/redhat-developer/intellij-quarkus/blob/efc6c6afa78f28b95f55f8c0f71e6585200e7e9d/src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/ChangeUtil.java#L79

`changes.add(Either.forLeft(converter.convertToTextDocumentEdit(0)));`

I will remove also the LOGGER static field in TextEditConverter which is never used.

**Comment by anusreelakshmi934** [comment]
> I will keep this method and I will consume it here:
> 
> https://github.com/redhat-developer/intellij-quarkus/blob/efc6c6afa78f28b95f55f8c0f71e6585200e7e9d/src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/ChangeUtil.java#L79
> 
> `changes.add(Either.forLeft(converter.convertToTextDocumentEdit(0)));`
> 
> I will remove also the LOGGER static field in TextEditConverter which is never used.

Are you planning to proceed with the proposed changes and create a separate PR, or should I make modifications to the current PR? However, the deprecated VersionedTextDocumentIdentifier.<init>(Integer) method is still being used.

**Comment by angelozerr** [comment]
> > I will keep this method and I will consume it here:
> > 
> > https://github.com/redhat-developer/intellij-quarkus/blob/efc6c6afa78f28b95f55f8c0f71e6585200e7e9d/src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/ChangeUtil.java#L79
> > 
> > `changes.add(Either.forLeft(converter.convertToTextDocumentEdit(0)));`
> > 
> > I will remove also the LOGGER static field in TextEditConverter which is never used.
> 
> Are you planning to proceed with the proposed changes and create a separate PR, or should I make modifications to the current PR? However, the deprecated VersionedTextDocumentIdentifier.<init>(Integer) method is still being used.

As you wish.

**Comment by anusreelakshmi934** [comment]
> > > I will keep this method and I will consume it here:
> > > https://github.com/redhat-developer/intellij-quarkus/blob/efc6c6afa78f28b95f55f8c0f71e6585200e7e9d/src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/ChangeUtil.java#L79
> > > 
> > > `changes.add(Either.forLeft(converter.convertToTextDocumentEdit(0)));`
> > > I will remove also the LOGGER static field in TextEditConverter which is never used.
> > 
> > 
> > Are you planning to proceed with the proposed changes and create a separate PR, or should I make modifications to the current PR? However, the deprecated VersionedTextDocumentIdentifier.(Integer) method is still being used.
> 
> As you wish.

I'll make the modifications and update the PR tomorrow. Thanks

**Comment by angelozerr** [comment]
Thanks!

**Comment by anusreelakshmi934** [comment]
@angelozerr I have modified the PR. Please take a look. Thanks!

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/TextEditConverter.java [hunk 1]
```diff
@@ -63,7 +62,7 @@ public List<org.eclipse.lsp4j.TextEdit> convert() {
 	}
 
 	public TextDocumentEdit convertToTextDocumentEdit(int version) {
-		VersionedTextDocumentIdentifier identifier = new VersionedTextDocumentIdentifier(version);
+		VersionedTextDocumentIdentifier identifier = new VersionedTextDocumentIdentifier(uri, version);
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/TextEditConverter.java:65]: Remove the line code which set the uri since you initialized uri in the constructor

**Review by angelozerr — CHANGES_REQUESTED** [review]

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/TextEditConverter.java (hunk 1 above)
Comment (anusreelakshmi934) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/java/TextEditConverter.java:65]: I have removed it. Thanks

**Review by angelozerr — APPROVED** [review]

**Comment by angelozerr** [comment]
Thanks @anusreelakshmi934 !

**Comment by anusreelakshmi934** [comment]
Hi @angelozerr I can see that some tests are failing. I am not sure how to run your tests locally. Could you verify that? Thanks

**Comment by angelozerr** [comment]
Dont worry with test failure. We are aware about that and @sbouchet is working on it https://github.com/redhat-developer/intellij-quarkus/issues/1435

**Comment by anusreelakshmi934** [comment]
> Dont worry with test failure. We are aware about that and @sbouchet is working on it #1435

Ok. Thanks
