### PR TITLE
fix: debounce classpath/source change events

### LINKED ISSUE #916: Debounce classpath/source change events
- Clone https://github.com/quarkusio/registry.quarkus.io and open it in IJ
- Open src/main/resources/application.properties (not sure it's necessary)
- Open LSP consoles view / Tools for Microprofile, right click in console to clear all.
- Open pom.xml 
- change `<quarkus.version>3.1.0.Final</quarkus.version>` to `<quarkus.version>3.0.1.Final</quarkus.version>`
- save pom.xml
- look at amount of requests in LSP console and weep.

59 `microprofile/projectInfo` requests
237 `microprofile/propertiesChanged` notifications

```
[Trace - 06:16:37 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:37 PM] Received request 'microprofile/projectInfo - (50)'.
[Trace - 06:16:37 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending response 'microprofile/projectInfo - (50)'. Processing request took 580ms
[Trace - 06:16:38 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Received request 'microprofile/projectInfo - (51)'.
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending response 'microprofile/projectInfo - (51)'. Processing request took 175ms
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Received request 'microprofile/projectInfo - (52)'.
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending response 'microprofile/projectInfo - (52)'. Processing request took 170ms
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Received request 'microprofile/projectInfo - (53)'.
[Trace - 06:16:38 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Sending response 'microprofile/projectInfo - (53)'. Processing request took 119ms
[Trace - 06:16:38 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:38 PM] Received request 'microprofile/projectInfo - (54)'.
[Trace - 06:16:38 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending response 'microprofile/projectInfo - (54)'. Processing request took 148ms
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Received request 'microprofile/projectInfo - (55)'.
[Trace - 06:16:39 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending response 'microprofile/projectInfo - (55)'. Processing request took 150ms
[Trace - 06:16:39 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Received request 'microprofile/projectInfo - (56)'.
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending response 'microprofile/projectInfo - (56)'. Processing request took 140ms
[Trace - 06:16:39 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Received request 'microprofile/projectInfo - (57)'.
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending response 'microprofile/projectInfo - (57)'. Processing request took 96ms
[Trace - 06:16:39 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Received request 'microprofile/projectInfo - (58)'.
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending response 'microprofile/projectInfo - (58)'. Processing request took 133ms
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Received request 'microprofile/projectInfo - (59)'.
[Trace - 06:16:39 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Sending response 'microprofile/projectInfo - (59)'. Processing request took 102ms
[Trace - 06:16:39 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:39 PM] Received request 'microprofile/projectInfo - (60)'.
[Trace - 06:16:39 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending response 'microprofile/projectInfo - (60)'. Processing request took 154ms
[Trace - 06:16:40 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Received request 'microprofile/projectInfo - (61)'.
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending response 'microprofile/projectInfo - (61)'. Processing request took 95ms
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Received request 'microprofile/projectInfo - (62)'.
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending response 'microprofile/projectInfo - (62)'. Processing request took 134ms
[Trace - 06:16:40 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Received request 'microprofile/projectInfo - (63)'.
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending response 'microprofile/projectInfo - (63)'. Processing request took 94ms
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Received request 'microprofile/projectInfo - (64)'.
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending response 'microprofile/projectInfo - (64)'. Processing request took 146ms
[Trace - 06:16:40 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Received request 'microprofile/projectInfo - (65)'.
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Sending response 'microprofile/projectInfo - (65)'. Processing request took 120ms
[Trace - 06:16:40 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:40 PM] Received request 'microprofile/projectInfo - (66)'.
[Trace - 06:16:40 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending response 'microprofile/projectInfo - (66)'. Processing request took 118ms
[Trace - 06:16:41 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Received request 'microprofile/projectInfo - (67)'.
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending response 'microprofile/projectInfo - (67)'. Processing request took 131ms
[Trace - 06:16:41 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Received request 'microprofile/projectInfo - (68)'.
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending response 'microprofile/projectInfo - (68)'. Processing request took 123ms
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Received request 'microprofile/projectInfo - (69)'.
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending response 'microprofile/projectInfo - (69)'. Processing request took 118ms
[Trace - 06:16:41 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Received request 'microprofile/projectInfo - (70)'.
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending response 'microprofile/projectInfo - (70)'. Processing request took 132ms
[Trace - 06:16:41 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Received request 'microprofile/projectInfo - (71)'.
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending response 'microprofile/projectInfo - (71)'. Processing request took 107ms
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Received request 'microprofile/projectInfo - (72)'.
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:41 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending response 'microprofile/projectInfo - (72)'. Processing request took 131ms
[Trace - 06:16:42 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received request 'microprofile/projectInfo - (73)'.
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending response 'microprofile/projectInfo - (73)'. Processing request took 97ms
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received request 'microprofile/projectInfo - (74)'.
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending response 'microprofile/projectInfo - (74)'. Processing request took 120ms
[Trace - 06:16:42 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received request 'microprofile/projectInfo - (75)'.
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending response 'microprofile/projectInfo - (75)'. Processing request took 94ms
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received request 'microprofile/projectInfo - (76)'.
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending response 'microprofile/projectInfo - (76)'. Processing request took 112ms
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received request 'microprofile/projectInfo - (77)'.
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending response 'microprofile/projectInfo - (77)'. Processing request took 84ms
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received request 'microprofile/projectInfo - (78)'.
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending response 'microprofile/projectInfo - (78)'. Processing request took 120ms
[Trace - 06:16:42 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Received request 'microprofile/projectInfo - (79)'.
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:42 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending response 'microprofile/projectInfo - (79)'. Processing request took 121ms
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:43 PM] Received request 'microprofile/projectInfo - (80)'.
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending response 'microprofile/projectInfo - (80)'. Processing request took 87ms
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received request 'microprofile/projectInfo - (81)'.
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending response 'microprofile/projectInfo - (81)'. Processing request took 99ms
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received request 'microprofile/projectInfo - (82)'.
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending response 'microprofile/projectInfo - (82)'. Processing request took 118ms
[Trace - 06:16:43 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received request 'microprofile/projectInfo - (83)'.
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending response 'microprofile/projectInfo - (83)'. Processing request took 116ms
[Trace - 06:16:43 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received request 'microprofile/projectInfo - (84)'.
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending response 'microprofile/projectInfo - (84)'. Processing request took 113ms
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received request 'microprofile/projectInfo - (85)'.
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending response 'microprofile/projectInfo - (85)'. Processing request took 103ms
[Trace - 06:16:43 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Received request 'microprofile/projectInfo - (86)'.
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:43 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending response 'microprofile/projectInfo - (86)'. Processing request took 115ms
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Received request 'microprofile/projectInfo - (87)'.
[Trace - 06:16:44 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending response 'microprofile/projectInfo - (87)'. Processing request took 91ms
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Received request 'microprofile/projectInfo - (88)'.
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending response 'microprofile/projectInfo - (88)'. Processing request took 115ms
[Trace - 06:16:44 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Received request 'microprofile/projectInfo - (89)'.
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending response 'microprofile/projectInfo - (89)'. Processing request took 128ms
[Trace - 06:16:44 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Received request 'microprofile/projectInfo - (90)'.
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending response 'microprofile/projectInfo - (90)'. Processing request took 99ms
[Trace - 06:16:44 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Received request 'microprofile/projectInfo - (91)'.
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending response 'microprofile/projectInfo - (91)'. Processing request took 119ms
[Trace - 06:16:44 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Received request 'microprofile/projectInfo - (92)'.
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending response 'microprofile/projectInfo - (92)'. Processing request took 99ms
[Trace - 06:16:44 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Received request 'microprofile/projectInfo - (93)'.
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:44 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending response 'microprofile/projectInfo - (93)'. Processing request took 116ms
[Trace - 06:16:45 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Received request 'microprofile/projectInfo - (94)'.
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending response 'microprofile/projectInfo - (94)'. Processing request took 91ms
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Received request 'microprofile/projectInfo - (95)'.
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending response 'microprofile/projectInfo - (95)'. Processing request took 128ms
[Trace - 06:16:45 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Received request 'microprofile/projectInfo - (96)'.
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending response 'microprofile/projectInfo - (96)'. Processing request took 139ms
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Received request 'microprofile/projectInfo - (97)'.
[Trace - 06:16:45 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending response 'microprofile/projectInfo - (97)'. Processing request took 112ms
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Received request 'microprofile/projectInfo - (98)'.
[Trace - 06:16:45 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending response 'microprofile/projectInfo - (98)'. Processing request took 147ms
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Received request 'microprofile/projectInfo - (99)'.
[Trace - 06:16:45 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Sending response 'microprofile/projectInfo - (99)'. Processing request took 89ms
[Trace - 06:16:45 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:45 PM] Received request 'microprofile/projectInfo - (100)'.
[Trace - 06:16:45 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending response 'microprofile/projectInfo - (100)'. Processing request took 147ms
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Received request 'microprofile/projectInfo - (101)'.
[Trace - 06:16:46 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending response 'microprofile/projectInfo - (101)'. Processing request took 104ms
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Received request 'microprofile/projectInfo - (102)'.
[Trace - 06:16:46 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending response 'microprofile/projectInfo - (102)'. Processing request took 122ms
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Received request 'microprofile/projectInfo - (103)'.
[Trace - 06:16:46 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending response 'microprofile/projectInfo - (103)'. Processing request took 95ms
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Received request 'microprofile/projectInfo - (104)'.
[Trace - 06:16:46 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending response 'microprofile/projectInfo - (104)'. Processing request took 127ms
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Received request 'microprofile/projectInfo - (105)'.
[Trace - 06:16:46 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending response 'microprofile/projectInfo - (105)'. Processing request took 104ms
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Received request 'microprofile/projectInfo - (106)'.
[Trace - 06:16:46 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Sending response 'microprofile/projectInfo - (106)'. Processing request took 108ms
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:46 PM] Received request 'microprofile/projectInfo - (107)'.
[Trace - 06:16:46 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:46 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:47 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:47 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:47 PM] Sending response 'microprofile/projectInfo - (107)'. Processing request took 96ms
[Trace - 06:16:47 PM] Received notification 'textDocument/publishDiagnostics'
[Trace - 06:16:47 PM] Sending notification 'microprofile/propertiesChanged'
[Trace - 06:16:47 PM] Received request 'microprofile/projectInfo - (108)'.
[Trace - 06:16:47 PM] Sending response 'microprofile/projectInfo - (108)'. Processing request took 82ms
[Trace - 06:16:47 PM] Received notification 'textDocument/publishDiagnostics'
```

### LINKED ISSUE #958: 1000s of LSP events in Qute console, after reopening a project
- open [quarkus-blast](https://github.com/ia3andy/quarkus-blast)
- open src/main/resources/templates/QuarkusBlast/index.html
- open src/main/java/rest/QuarkusBlast.java
- open LSP console view, select Qute console, set message level
- close IntelliJ IDEA
- re-open quarkus-blast
- in the Qute LSP console view, ~1000 lines of messages can be seen
- close and reopen the quarkus-blast project (don't close IDEA)
- in the Qute LSP console view, ~11000 lines of messages can be seen
 
Might be caused by the QuarkusProjectService which never unsubscribes itself from the message bus, when disposed

https://github.com/redhat-developer/intellij-quarkus/blob/de21506ece1ee2fbf54eba5555f1d2c8242a90f3/src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusProjectService.java#L111

### PR DESCRIPTION
**Pull request by angelozerr**
fix: debounce classpath/source change events (#916)

Fixes #916
Fixes #958

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java [hunk 1]
```diff
@@ -92,28 +93,27 @@ private void notifyDataModelChanged(Set<String> uris) {
   }
 
   @Override
-  public void libraryUpdated(Library library) {
+  public void librariesChanged() {
     if (isDisposed()) {
       // The language client has been disposed, ignore the changed of library
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java:98]: ignore changes in libraries

File: src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java [hunk 2]
```diff
@@ -92,28 +93,27 @@ private void notifyDataModelChanged(Set<String> uris) {
...
     uris.add(PsiQuteProjectUtils.getProjectURI(getProject()));
-    notifyDataModelChanged(uris);
+    notifyQuteDataModelChanged(uris);
   }
 
   @Override
-  public void sourceUpdated(List<Pair<Module, VirtualFile>> sources) {
+  public void sourceFilesChanged(Set<Pair<VirtualFile, Module>> sources) {
     if (isDisposed()) {
       // The language client has been disposed, ignore the changed of Java source files
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java:109]: ignore changes in Java source files

**Review by fbricon — CHANGES_REQUESTED** [review]
please also fix the commit message

File: src/main/resources/META-INF/plugin.xml [hunk 3]
```diff
@@ -1,4 +1,5 @@
 <idea-plugin>
+  <idea-version since-build="213"/>
```
Comment (fbricon) [inline src/main/resources/META-INF/plugin.xml:2]: please change it L238 instead

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+        WorkspaceModelTopics.getInstance(project).subscribeAfterModuleLoading(connection, listener);
+        // Track update of update of Psi Java, properties files
+        PsiManager.getInstance(project).addPsiTreeChangeListener(listener, project);
+    }
+
+    @Override
+    public void dispose() {
+        this.sourcesChanged.dispose();
+        this.connection.disconnect();
+        PsiManager.getInstance(project).removePsiTreeChangeListener(listener);
```
[the remark this answers is not in the document]
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java:59]: why?

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java [hunk 5]
```diff
@@ -1,126 +1,154 @@
...
-import com.intellij.openapi.vfs.VirtualFileManager;
-import com.intellij.openapi.vfs.newvfs.BulkFileListener;
-import com.intellij.openapi.vfs.newvfs.events.VFileContentChangeEvent;
-import com.intellij.openapi.vfs.newvfs.events.VFileCreateEvent;
-import com.intellij.openapi.vfs.newvfs.events.VFileDeleteEvent;
-import com.intellij.openapi.vfs.newvfs.events.VFileEvent;
 import com.intellij.util.messages.MessageBusConnection;
-import com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.ls.PsiUtilsLSImpl;
+import com.redhat.devtools.intellij.quarkus.classpath.ClasspathResourceChangeManager;
+import org.apache.commons.lang3.tuple.Pair;
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java:22]: com.intellij.openapi.util.Pair;

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java [hunk 6]
```diff
@@ -0,0 +1,131 @@
...
+import com.intellij.openapi.vfs.newvfs.events.VFileEvent;
+import com.intellij.psi.PsiFile;
+import com.intellij.psi.PsiTreeChangeAdapter;
+import com.intellij.psi.PsiTreeChangeEvent;
+import com.intellij.workspaceModel.ide.WorkspaceModelChangeListener;
+import com.intellij.workspaceModel.storage.VersionedStorageChange;
+import com.intellij.workspaceModel.storage.bridgeEntities.LibraryEntity;
+import com.redhat.devtools.intellij.lsp4ij.LSPIJUtils;
+import com.redhat.devtools.intellij.lsp4mp4ij.psi.core.project.PsiMicroProfileProjectManager;
+import org.apache.commons.lang3.tuple.Pair;
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java:19]: com.intellij.openapi.util.Pair;

File: src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java [hunk 7]
```diff
@@ -24,6 +25,7 @@
 import com.redhat.devtools.intellij.quarkus.QuarkusModuleUtil;
 import com.redhat.devtools.intellij.quarkus.QuarkusProjectService;
 import com.redhat.devtools.intellij.lsp4ij.IndexAwareLanguageClient;
+import com.redhat.devtools.intellij.quarkus.classpath.ClasspathResourceChangeManager;
 import org.apache.commons.lang3.tuple.Pair;
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java:29]: com.intellij.openapi.util.Pair

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+import com.intellij.openapi.components.ServiceManager;
+import com.intellij.openapi.module.Module;
+import com.intellij.openapi.project.Project;
+import com.intellij.openapi.vfs.VirtualFile;
+import com.intellij.openapi.vfs.VirtualFileManager;
+import com.intellij.psi.PsiManager;
+import com.intellij.util.messages.MessageBusConnection;
+import com.intellij.util.messages.Topic;
+import com.intellij.workspaceModel.ide.WorkspaceModelTopics;
+import org.apache.commons.lang3.tuple.Pair;
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java:13]: com.intellij.openapi.util.Pair

**Review by fbricon — CHANGES_REQUESTED** [review]

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java:59]: gut feeling. Feel free to ignore that question

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java [hunk 9]
```diff
@@ -0,0 +1,131 @@
...
+        handleChangedPsiTree(event);
+    }
+
+    @Override
+    public void propertyChanged(@NotNull PsiTreeChangeEvent event) {
+        handleChangedPsiTree(event);
+    }
+
+    private void handleChangedPsiTree(PsiTreeChangeEvent event) {
+        PsiFile psiFile = event.getFile();
```
[the remark this answers is not in the document]
Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java:83]: you're checking event.getFile() for null, why not psiFile.getVirtualFile() instead, since this is what is being used later on?

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java [hunk 10]
```diff
@@ -0,0 +1,61 @@
...
+        this.sourcesChanged = new SourceFileChangeNotifier(files ->
+                project.getMessageBus().syncPublisher(ClasspathResourceChangeManager.TOPIC).sourceFilesChanged(files)
+        );
+        listener = new ClasspathRessourceChangedListener(project, sourcesChanged);
+        connection = project.getMessageBus().connect();
+        // Track delete, create, update of file
+        connection.subscribe(VirtualFileManager.VFS_CHANGES, listener);
+        // Track end of Java libraries update
+        WorkspaceModelTopics.getInstance(project).subscribeAfterModuleLoading(connection, listener);
+        // Track update of update of Psi Java, properties files
```
[the remark this answers is not in the document]
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java [hunk 11]
```diff
@@ -0,0 +1,131 @@
+package com.redhat.devtools.intellij.quarkus.classpath;
```
[the remark this answers is not in the document]
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java:14]: fixed and I add Javadoc in class header

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java [hunk 12]
```diff
@@ -0,0 +1,61 @@
+package com.redhat.devtools.intellij.quarkus.classpath;
```
[the remark this answers is not in the document]
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java]: fixed and I add Javadoc in class header

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/SourceFileChangeNotifier.java [hunk 13]
```diff
@@ -0,0 +1,60 @@
+package com.redhat.devtools.intellij.quarkus.classpath;
```
[the remark this answers is not in the document]
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/SourceFileChangeNotifier.java:14]: fixed and I add Javadoc in class header

File: src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java (hunk 1 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java (hunk 2 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/qute/lsp/QuteLanguageClient.java]: fixed

File: src/main/resources/META-INF/plugin.xml (hunk 3 above)
Comment (angelozerr) [reply src/main/resources/META-INF/plugin.xml]: Good catch, fixed

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java (hunk 8 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangeManager.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java (hunk 7 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java (hunk 6 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/SourceFileChangeNotifier.java [hunk 14]
```diff
@@ -0,0 +1,60 @@
+package com.redhat.devtools.intellij.quarkus.classpath;
+
+import com.intellij.openapi.Disposable;
+import com.intellij.openapi.module.Module;
+import com.intellij.openapi.vfs.VirtualFile;
+import org.apache.commons.lang3.tuple.Pair;
```
[the remark this answers is not in the document]
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/SourceFileChangeNotifier.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java [hunk 15]
```diff
@@ -0,0 +1,189 @@
...
+
+    private static final Class libraryClass;
+
+    static {
+        libraryClass = getLibraryClass();
+        // here Java reflection is used to try to support several IJ versions
+        if (libraryClass == null) {
+            LOGGER.warn("Cannot find LibraryEntity class '" +
+                    Arrays.stream(LIBRARY_ENTITY_CLASSES)
+                            .collect(Collectors.joining(",")) + "' in classpath.");
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java:174]: String.join(",", LIBRARY_ENTITY_CLASSES)

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathRessourceChangedListener.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathLibraryChangedListener.java [hunk 16]
```diff
@@ -0,0 +1,76 @@
...
+import org.slf4j.LoggerFactory;
+
+/**
+ * Classpath resource changed listener used to track update of libraries.
+ */
+class ClasspathLibraryChangedListener extends WorkspaceModelChangeListenerBridge {
+
+    private static final Logger LOGGER = LoggerFactory.getLogger(ClasspathLibraryChangedListener.class);
+
+    private static final String[] LIBRARY_ENTITY_CLASSES = {"com.intellij.workspaceModel.storage.bridgeEntities.LibraryEntity", "com.intellij.workspaceModel.storage.bridgeEntities.api.LibraryEntityImpl", "com.intellij.platform.workspace.jps.entities.LibraryEntity"};
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathLibraryChangedListener.java:31]: please document which class corresponds to which version of IDEA

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathLibraryChangedListener.java [hunk 17]
```diff
@@ -0,0 +1,76 @@
...
+
+    private final Project project;
+
+    public ClasspathLibraryChangedListener(Project project) {
+        super();
+        this.project = project;
+        libraryClass = getLibraryClass();
+        // here Java reflection is used to try to support several IJ versions
+        if (libraryClass == null) {
+            LOGGER.warn("Cannot find LibraryEntity class '" + String.join(",", LIBRARY_ENTITY_CLASSES) + "' in classpath.");
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathLibraryChangedListener.java:43]: also LOGGER.warn("Reacting to classpath changes is not supported in this version of Intellij IDEA")

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedManager.java [hunk 18]
```diff
@@ -0,0 +1,109 @@
...
+        }
+        // Send source files changed in debounce mode
+        this.sourcesChanged = new SourceFileChangeNotifier(files ->
+                project.getMessageBus().syncPublisher(ClasspathResourceChangedManager.TOPIC).sourceFilesChanged(files)
+        );
+        listener = new ClasspathSourceFileChangedListener(project, sourcesChanged);
+        connection = project.getMessageBus().connect();
+        // Track end of Java libraries update
+        WorkspaceModelTopicsBridge workspaceModelTopicsBridge = new WorkspaceModelTopicsBridge();
+        Object libraryChangedListener = new ClasspathLibraryChangedListener(project).getProxyInstance();
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedManager.java:85]: no need to create a proxy instance if workspaceModelTopicsBridge.CHANGED == null

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/bridge/VersionedStorageChangeBridge.java [hunk 19]
```diff
@@ -0,0 +1,70 @@
...
+        Method getChangesMethod = getChangesMethods.get(clazz);
+        if (getChangesMethod != null) {
+            return getChangesMethod;
+        }
+        Method[] methods = clazz.getDeclaredMethods();
+        for (Method method : methods) {
+            if ("getChanges".equals(method.getName())) {
+                method.setAccessible(true);
+                getChangesMethod = method;
+                getChangesMethods.put(clazz, getChangesMethod);
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/classpath/bridge/VersionedStorageChangeBridge.java:63]: break here

**Comment by fbricon** [comment]
Tests fail:
```
Test testConfigPropertyNameResolveExpression FAILED (14.7s)

  java.lang.AssertionError: expected:<MarkupContent [
    kind = "markdown"
    value = "`greeting.message = salutations` *in* [META-INF/microprofile-config.properties](file:///tmp/unitTest_configPropertyNameResolveExpression_2RTchAIsIGwgDevZZaFmFJk7Ek9/testConfigPropertyNameResolveExpression_2RTch4wMbMG5NIFipP377WAhq0t/config-hover23/src/main/resources/META-INF/microprofile-config.properties)"
  ]> but was:<MarkupContent [
    kind = "markdown"
    value = "`greeting.message = hello` *in* [META-INF/microprofile-config.properties](file:///tmp/unitTest_configPropertyNameResolveExpression_2RTchAIsIGwgDevZZaFmFJk7Ek9/testConfigPropertyNameResolveExpression_2RTch4wMbMG5NIFipP377WAhq0t/config-hover23/src/main/resources/META-INF/microprofile-config.properties)"
  ]>
      at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.config.java.MicroProfileConfigJavaHoverTest.testConfigPropertyNameResolveExpression(MicroProfileConfigJavaHoverTest.java:269)

```

and 

```
Test testUrlCodeLensPropertiesWithPropertyExpression FAILED (19s)

  org.junit.ComparisonFailure: expected:<...//restcountries.url/[${asdf}]/v2/name/{name}> but was:<...//restcountries.url/[rest]/v2/name/{name}>
      at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.restclient.java.MicroProfileRestClientJavaCodeLensTest.assertCodeLenses(MicroProfileRestClientJavaCodeLensTest.java:244)

```

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java [hunk 20]
```diff
@@ -1,126 +1,165 @@
...
 import com.intellij.openapi.vfs.VirtualFile;
-import com.intellij.openapi.vfs.VirtualFileManager;
-import com.intellij.openapi.vfs.newvfs.BulkFileListener;
-import com.intellij.openapi.vfs.newvfs.events.VFileContentChangeEvent;
-import com.intellij.openapi.vfs.newvfs.events.VFileCreateEvent;
-import com.intellij.openapi.vfs.newvfs.events.VFileDeleteEvent;
-import com.intellij.openapi.vfs.newvfs.events.VFileEvent;
 import com.intellij.util.messages.MessageBusConnection;
-import com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.ls.PsiUtilsLSImpl;
+import com.redhat.devtools.intellij.quarkus.classpath.ClasspathResourceChangedManager;
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java:22]: lsp4mpij should depend on quarkus packages

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedListener.java [hunk 21]
```diff
@@ -0,0 +1,236 @@
...
+    ClasspathResourceChangedListener(ClasspathResourceChangedManager manager) {
+        this.manager = manager;
+    }
+
+    // Track modules changed
+
+    public CompletableFuture<Void> processModules() {
+        return CompletableFuture.runAsync(() -> {
+            for (var module : ModuleManager.getInstance(manager.getProject()).getModules()) {
+                LOGGER.info("Calling ensure from processModules");
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedListener.java:66]: calling checkQuarkusLibrary rather?

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedListener.java [hunk 22]
```diff
@@ -0,0 +1,236 @@
...
+/**
+ * Classpath resource changed listener used to track update of Java source and microprofile-config.properties files.
+ */
+class ClasspathResourceChangedListener extends PsiTreeChangeAdapter implements BulkFileListener, LibraryTable.Listener, ModuleListener {
+
+    private static final Logger LOGGER = LoggerFactory.getLogger(ClasspathResourceChangedListener.class);
+
+    private final ClasspathResourceChangedManager manager;
+
+    private final Set<Module> modulesBeingEnsured = new HashSet<>();
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedListener.java:55]: quarkusModules or checkedQuarkusModules?

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java (hunk 20 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProjectManager.java]: I moved ClasspathResourceChangedManager to lsp4mp4ij which have no dependecies to quarkus.

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedListener.java (hunk 22 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedListener.java]: We must not use Quarkus as it is MicroProfile.

File: src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedListener.java (hunk 21 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/classpath/ClasspathResourceChangedListener.java]: We must not use Quarkus.

**Comment by angelozerr** [comment]
@fbricon CI build is working again!
