### PR TITLE
fix: remove usage of VfsUtil.findFileByURL

### LINKED ISSUE #856: Some codelens don't work in WSL2
The `Open template` code lens from a Java file, or the `Open type` header code lens in a qute template don't work, when the project is opened from a WSL2 environment. No exceptions. Just don't work.

The REST endpoint codelens work though.

Might be something related to #735, although sneakier.

### PR DESCRIPTION
**Pull request by fbricon**
The problem (and the fix) is similar to #735
Fixes #856

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java [hunk 1]
```diff
@@ -248,11 +241,7 @@ public static VirtualFile findResourceFor(URI uri) {
     }
 
     public static VirtualFile findResourceFor(String uri) {
-        try {
-            return VfsUtil.findFileByURL(new URL(uri));
-        } catch (MalformedURLException e) {
-            return null;
-        }
+        return VirtualFileManager.getInstance().findFileByUrl(VfsUtilCore.fixURLforIDEA(uri));
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java:244]: The fix that you did [PsiUtilsLSImpl.java](https://github.com/redhat-developer/intellij-quarkus/commit/16c76e76e34a4a9535e0ef38289b88a42a5d4f16#diff-78d1994d7563bb33170f619c2358419c78997895ce3284cc2aaa0bfe8827ba79) should use `LSPIJUtils.findResourceFor` to have this fix in one location.

Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/quarkus/lsp4ij/LSPIJUtils.java:244]: done
