### PR TITLE
fix: Modification to replace the usage of deprecated method DumbService.runReadActionInSmartMode(Computable)

### LINKED ISSUE #1420: Address usage of deprecated method 'DumbService.runReadActionInSmartMode(Computable)'
The deprecated method DumbService.runReadActionInSmartMode(Computable) is invoked in the following methods:

 - [x] ProjectLabelManager.getProjectLabelInfo(...)
 - [x]  PropertiesManager.findPropertyLocation(...)

### PR DESCRIPTION
**Pull request by dessina-devasia**
- Replaced deprecated method `DumbService.runReadActionInSmartMode(Computable)`
- Removed unused DumbService and other imports in related files
- Changed copyright year to 2025

Fixes #1420

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java [hunk 1]
```diff
@@ -222,7 +220,8 @@ public Location findPropertyLocation(VirtualFile file, String sourceType, String
     }
 
     public Location findPropertyLocation(Module module, String sourceType, String sourceField, String sourceMethod, IPsiUtils utils) {
-        return DumbService.getInstance(module.getProject()).runReadActionInSmartMode(() -> {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java:225]: Like you have removed ReadAction in ProjectLabelManager, should we need this wrap with ReadAction ?

Comment (dessina-devasia) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java:225]: @angelozerr Yes it must be.

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java:225]: That's very strange because this findPropertyLocation should be called also in a non blocking read action in the QuarkusLanguageClient.

Do you see trouble if you remove this ReadAction?

Comment (dessina-devasia) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java:225]: @angelozerr Removed the ReadAction.nonBlocking() as findPropertyLocation() is already executed in a NonBlocking ReadAction.
