### PR TITLE
fix: prevent ConcurrentModificationException in CancellationSupport.cancel

### LINKED ISSUE #1122: java.util.ConcurrentModificationException in CancellationSupport.cancel
I don't hnow how to reproduce it, but I had this error:

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.redhat.devtools.intellij.lsp4ij.internal.CancellationSupport.cancel(CancellationSupport.java:52)
	at com.redhat.devtools.intellij.lsp4ij.operations.codelens.LSPCodelensInlayProvider$1.createCodeLenses(LSPCodelensInlayProvider.java:118)
	at com.redhat.devtools.intellij.lsp4ij.operations.codelens.LSPCodelensInlayProvider$1.collect(LSPCodelensInlayProvider.java:83)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:91)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$0(InlayHintsPass.kt:46)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:142)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:110)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:62)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation(InlayHintsPass.kt:37)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:185)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

### PR DESCRIPTION
**Pull request by fbricon**
Fixes #1122

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java [hunk 1]
```diff
@@ -32,7 +32,7 @@ public class CancellationSupport implements CancelChecker {
 	private boolean cancelled;
 
 	public CancellationSupport() {
-		this.futuresToCancel = new ArrayList<CompletableFuture<?>>();
+		this.futuresToCancel = new CopyOnWriteArrayList<>();
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: I think the proper fix is to forbid the add future if it is cancelled. In other words the first line of execute m'étais should be checkCancelled()

Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: So a CancellationSupport is used for a single request? Because once cancelled once, then it can never be reused

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: Yes it is the idea

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: The main idea is to cancel previous requests for à given opération. A cancel support is used to cancel those prévious requests.

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: In other words when cancel support is canceled it cannot be reused

Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: even if you do 
```java
	public <T> CompletableFuture<T> execute(CompletableFuture<T> future) {
		if (!cancelled) {
			this.futuresToCancel.add(future);
		}
		return future;
	}
```

callers will still join on the original future, returning null would be very inconvenient as lots of places would have to adapt

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: I think when cancel support is cancelled we should cancel the future which is add whenbexecute is callled and throw a cannellableexception to stop the process

Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: you mean 
```java
	public <T> CompletableFuture<T> execute(CompletableFuture<T> future) {
		if (cancelled) {
			future.cancel(true);
		} else {
			this.futuresToCancel.add(future);
		}
		return future;
	}

```

where do you need to explicitly throw a cancellable exception?

Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: or 
```java
public <T> CompletableFuture<T> execute(CompletableFuture<T> future) {
		checkCanceled(); // throws CancellationException if cancelled
		this.futuresToCancel.add(future);
		return future;
	}
```
?

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: you mean 
```java
	public <T> CompletableFuture<T> execute(CompletableFuture<T> future) {
		if (cancelled) {
			future.cancel(true);
                        checkCancelded
		} else {
			this.futuresToCancel.add(future);
		}
		return future;
	}

```

Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:35]: done

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java [hunk 2]
```diff
@@ -10,10 +10,10 @@
  ******************************************************************************/
 package com.redhat.devtools.intellij.lsp4ij.internal;
 
-import java.util.ArrayList;
 import java.util.List;
 import java.util.concurrent.CancellationException;
 import java.util.concurrent.CompletableFuture;
+import java.util.concurrent.CopyOnWriteArrayList;
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:16]: I think we can use a simple arraylist

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java [hunk 3]
```diff
@@ -32,20 +32,25 @@ public class CancellationSupport implements CancelChecker {
...
-		this.futuresToCancel = new ArrayList<CompletableFuture<?>>();
+		this.futuresToCancel = new CopyOnWriteArrayList<>();
 		this.cancelled = false;
 	}
 
 	public <T> CompletableFuture<T> execute(CompletableFuture<T> future) {
-		this.futuresToCancel.add(future);
+		if (cancelled) {
+			future.cancel(true);
+			checkCanceled();
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:42]: After reading again the lsp opérations which catch ProcessCanceledException I think we should throw ProcessCanceledException instead of calling checkedCancelled or update opérations to catch CancellationException

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java (hunk 2 above)
Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:16]: copyonwritearraylist should not impact performance, as the list will stay small. At least it'll provide the guarantee there will be no concurrent modifications exception, how unlikely that be

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:16]: OK lets keep like this

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java (hunk 3 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/internal/CancellationSupport.java:42]: @fbricon once the comment will be fixed we can merge it

**Comment by angelozerr** [comment]
Thanks @fbricon !
