### PR TITLE
fix: Bind language servers to Project instead of Module

### LINKED ISSUE #891: Bind language servers to Project instead of Module

### PR DESCRIPTION
**Pull request by angelozerr**
fix: Bind language servers to Project instead of Module

Fixes #891

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java [hunk 1]
```diff
@@ -793,7 +793,7 @@ private CompletableFuture<LanguageServer> connect(@Nonnull URI absolutePath, Doc
 
         VirtualFile file = FileDocumentManager.getInstance().getFile(document);
         if (file != null && file.exists()) {
-            watchProject(LSPIJUtils.getProject(file), false);
+            watchProject(LSPIJUtils.getModule(file), false);
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java:796]: maybe rename to watchModule

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java [hunk 2]
```diff
@@ -366,7 +366,7 @@ public synchronized void start() throws LanguageServerException {
                         final Map<URI, Document> toReconnect = filesToReconnect;
                         initializeFuture.thenRunAsync(() -> {
                             if (this.initialProject != null) {
-                                watchProject(this.initialProject, true);
+                                //watchProject(this.initialProject, true);
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java:369]: why?

**Comment by fbricon** [comment]
I tested it on https://github.com/quarkiverse/quarkus-ironjacamar, which is multimodule, didn't see any problem. LGTM

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java (hunk 1 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java]: I remove this code since we don't support workspace folder.

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java (hunk 2 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java]: I remove this code since we don't support workspace folder.

**Comment by angelozerr** [comment]
@fbricon is ready now, I have removed all workspace folder support.

@mfortunat this PR should fix your problem with your multi-module https://github.com/redhat-developer/intellij-quarkus/issues/1089#issuecomment-1710121155

**Comment by fbricon** [comment]
@angelozerr it looks like properties leak to unrelated projects. e.g. using https://github.com/quarkiverse/quarkus-ironjacamar

- set a new property in the integration test [application.properties]( https://github.com/quarkiverse/quarkus-ironjacamar/blob/main/integration-tests/artemis-jms/src/main/resources/application.properties)
- inject a ConfigProperty with the same name in [IronJacamarProcessor](https://github.com/quarkiverse/quarkus-ironjacamar/blob/main/deployment/src/main/java/io/quarkiverse/ironjacamar/deployment/IronJacamarProcessor.java#L61)

The downstream property is resolved on hover in the deployment module, even though it's not on that module's classpath

Screenshot 2023-09-07 at 18 55 50

**Comment by angelozerr** [comment]
@fbricon I think this problem is the same with just one module. We have problem with cache https://github.com/redhat-developer/intellij-quarkus/issues/860

To test this PR,I suggest that you create an application.properties in each module and on each module you define a class with ConfigProperty and you should see the proper properties in completion,validation for each module

**Comment by angelozerr** [comment]
> The downstream property is resolved on hover in the deployment module, even though it's not on that module's classpath

I think it is a feature coming from IJ himself, please check that with LSP console traces

**Comment by fbricon** [comment]
thanks @angelozerr
