### PR TITLE
fix: Too many non-blocking read actions submitted at once in LSPDiagnosticHandler

### LINKED ISSUE #1089: Too many non-blocking read actions submitted at once in LSPDiagnosticHandler
Guys, the newly released version 1.24.0.508 has another, repeating, issue.
IJ version is: "Build #IU-232.8660.185, built on July 26, 2023"

Stack trace:
-----
java.lang.Throwable: Too many non-blocking read actions submitted at once. Please use coalesceBy, BoundedTaskExecutor or another way of limiting the number of concurrently running threads.: 11 with similar stack traces are currently active
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.openapi.application.impl.SubmissionTracker.preventTooManySubmissions(SubmissionTracker.java:45)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.<init>(NonBlockingReadActionImpl.java:272)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.submit(NonBlockingReadActionImpl.java:227)
	at com.redhat.devtools.intellij.lsp4ij.operations.diagnostics.LSPDiagnosticHandler.accept(LSPDiagnosticHandler.java:52)
	at com.redhat.devtools.intellij.lsp4ij.operations.diagnostics.LSPDiagnosticHandler.accept(LSPDiagnosticHandler.java:38)
	at com.redhat.devtools.intellij.lsp4ij.client.LanguageClientImpl.publishDiagnostics(LanguageClientImpl.java:68)
	at jdk.internal.reflect.GeneratedMethodAccessor291.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at com.redhat.devtools.intellij.lsp4ij.LanguageServerWrapper.lambda$start$1(LanguageServerWrapper.java:334)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

### PR DESCRIPTION
**Pull request by angelozerr**
LSPDiagnosticHandler](fix: Too many non-blocking read actions submitted at once in LSPDiagnosticHandler

Fixes #1089

### CODE REVIEW

**Comment by angelozerr** [comment]
I created the PR but as I cannot reproduce it (hope @mfortunat could give us more info) , I cannot confirm that it fixes the issue.

I will try to emulate this usecase.

**Comment by angelozerr** [comment]
I retriggered the project index, and I type a lot of characters to handle diagnostics and I had no error.

I debug the IJ promise in the onError and I receive CANCELED exception which cancel the previous diagnostics.

I tried do do the same thing for all operations.

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LSPCompletableFuture.java [hunk 1]
```diff
@@ -54,12 +54,15 @@ public ResultOrError(R result, Exception error) {
     private final IndexAwareLanguageClient languageClient;
     private final String progressTitle;
     private final AtomicInteger nbAttempt;
+
+    private final Object coalesceBy;
     private CancellablePromise<ResultOrError<R>> nonBlockingReadActionPromise;
 
-    public LSPCompletableFuture(Function<ProgressIndicator, R> code, String progressTitle, IndexAwareLanguageClient languageClient) {
+    public LSPCompletableFuture(Function<ProgressIndicator, R> code, String progressTitle, IndexAwareLanguageClient languageClient, Object coalesceBy) {
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LSPCompletableFuture.java:61]: why Object and not a CoalesceByKey?

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LSPCompletableFuture.java:61]: because perhaps some services don't need that and have an object which defines an uniq hashcode

**Comment by fbricon** [comment]
I hammered the LS during reindexation, they didn't skip a beat. Impressive work @angelozerr!
