### PR TITLE
fix: Freeze with IDEA 2023.2 when it starts and indexing is processed

### LINKED ISSUE #1056: Freeze with IDEA 2023.2 when it starts and indexing is processed
I tested IJ Quarkus with `IDEA 2023.2` and it seems it is working.

The bad news is that (sometimes) when I start DEA 2023.2 and it processes idexing, the IDEA freezes totally and we cannot do nothing, just kiil it.

I think the solution is not to start language servers and not LSP consoles while it s indexing. I'm trying to figure out, but it is difficult to reproduce this freeze problem.

### PR DESCRIPTION
**Pull request by angelozerr**
fix: Freeze with IDEA 2023.2 when it starts and indexing is processed

Fixes #1056

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java [hunk 1]
```diff
@@ -303,7 +309,11 @@ public synchronized void start() throws LanguageServerException {
                 UnaryOperator<MessageConsumer> wrapper = consumer -> (message -> {
                     logMessage(message, consumer);
                     try {
-                        consumer.consume(message);
+                        if (!ApplicationManager.getApplication().isDispatchThread()) {
+                            CompletableFuture.runAsync(() -> consumer.consume(message));
+                        } else {
+                            consumer.consume(message);
+                        }
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java:316]: Should be 
```java
                        if (ApplicationManager.getApplication().isDispatchThread()) {
                            CompletableFuture.runAsync(() -> consumer.consume(message));
                        } else {
                            consumer.consume(message);
                        }
```

as to avoid running long-running operations on the dispatch thread

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java [hunk 2]
```diff
@@ -43,7 +46,16 @@ public LSPDiagnosticHandler(LanguageServerWrapper languageServerWrapper) {
...
+        if (ApplicationManager.getApplication().isReadAccessAllowed()) {
+            accept2(params);
+        } else {
+            ReadAction.nonBlocking(() -> accept2(params))
+                    .submit(AppExecutorUtil.getAppExecutorService());
+
+        }
+    }
+
+    public void accept2(PublishDiagnosticsParams params) {        //ApplicationManager.getApplication().runReadAction(() -> {
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java:58]: rename to "updateDiagnostics"

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java [hunk 3]
```diff
@@ -69,6 +81,6 @@ public void accept(PublishDiagnosticsParams params) {
             // {@link LSPDiagnosticAnnotator}.
             // which translates LSP Diagnostics into Intellij Annotation
             DaemonCodeAnalyzer.getInstance(module.getProject()).restart(psiFile);
-        });
+        //});
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java:84]: remove commented code

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java [hunk 4]
```diff
@@ -108,12 +108,10 @@ public MicroProfileProjectInfo getMicroProfileProjectInfo(Module module,
...
-            DumbService.getInstance(module.getProject()).runReadActionInSmartMode(() -> {
-                Query<PsiModifierListOwner> query = createSearchQuery(context);
-                beginSearch(context, monitor);
-                query.forEach((Consumer<? super PsiModifierListOwner>) psiMember -> collectProperties(psiMember, context, monitor));
-                endSearch(context, monitor);
-            });
+            Query<PsiModifierListOwner> query = createSearchQuery(context);
+            beginSearch(context, monitor);
+            query.forEach((Consumer<? super PsiModifierListOwner>) psiMember -> collectProperties(psiMember, context, monitor));
+            endSearch(context, monitor);
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java:114]: if an exception can be thrown during the search, then you prolly want to execute `endSearch` in a try/finally block

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java (hunk 1 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServerWrapper.java]: We need to di asynch in both usecase. fixed

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java (hunk 2 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java (hunk 3 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/diagnostics/LSPDiagnosticHandler.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java (hunk 4 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManager.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LSPCompletableFuture.java [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+                    // Index are not ready or the read action cannot be done, retry...
+                    var newPromise = nonBlockingReadActionPromise();
+                    bind(newPromise);
+                } else {
+                    // mark the completable future as error
+                    this.completeExceptionally(ex);
+                }
+            }
+        });
+        // On sucess...
```
[the remark this answers is not in the document]
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/client/LSPCompletableFuture.java]: fixed

File: src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServersRegistry.java [hunk 6]
```diff
@@ -15,6 +15,7 @@
 import com.intellij.openapi.editor.Document;
 import com.intellij.openapi.project.Project;
 import com.intellij.openapi.vfs.VirtualFile;
+import com.redhat.devtools.intellij.lsp4ij.client.LanguageClientImpl;
```
[the remark this answers is not in the document]
Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServersRegistry.java:18]: you just added an import without any other code change in that file

[the remark this answers is not in the document]
Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/lsp4ij/LanguageServersRegistry.java:18]: my bad, this is linked to the package change of that class

File: src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/DataModelProviderRegistry.java [hunk 7]
```diff
@@ -168,12 +169,13 @@ private void scanJavaClasses(Module javaProject, boolean excludeTestCode, List<Q
...
-			// Execute the search
-			beginSearch(context, subMonitor);
-			pattern.forEach((Consumer<Object>) psiMember -> collectDataModel(psiMember, context, mainMonitor));
-			endSearch(context, subMonitor);
+			if (pattern != null) {
+				SearchScope scope = createSearchScope(javaProject, scopes, excludeTestCode, subMonitor);
+				// Execute the search
+				beginSearch(context, subMonitor);
+				pattern.forEach((Consumer<Object>) psiMember -> collectDataModel(psiMember, context, mainMonitor));
+				endSearch(context, subMonitor);
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/DataModelProviderRegistry.java:177]: move endSearch to finally block

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/qute/psi/internal/template/datamodel/DataModelProviderRegistry.java]: fixed

**Comment by fbricon** [comment]
Thanks @angelozerr!
