### PR TITLE
fix: correctly treat optionals that dont have generics (#801)

### LINKED ISSUE #801: Cannot compute MicroProfile properties for the Java element 'PsiClass:CacheConfig'.
The following error appears when I edit an application.properties (https://github.com/quarkusio/registry.quarkus.io/blob/main/src/main/resources/application.properties specifically).

I am using Quarkus Tools 1.17.1.346

```java
Cannot compute MicroProfile properties for the Java element 'PsiClass:CacheConfig'.

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:152)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:214)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:214)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.processConfigMapping(QuarkusConfigMappingProvider.java:120)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.processAnnotation(QuarkusConfigMappingProvider.java:90)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.AbstractAnnotationTypeReferencePropertiesProvider.processAnnotation(AbstractAnnotationTypeReferencePropertiesProvider.java:58)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.AbstractAnnotationTypeReferencePropertiesProvider.collectProperties(AbstractAnnotationTypeReferencePropertiesProvider.java:48)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.collectProperties(PropertiesManager.java:126)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.lambda$getMicroProfileProjectInfo$1(PropertiesManager.java:103)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.lambda$getMicroProfileProjectInfo$2(PropertiesManager.java:103)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:149)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:100)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:87)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:78)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$getProjectInfo$2(QuarkusLanguageClient.java:112)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient.runTask(IndexAwareLanguageClient.java:97)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient$1.run(IndexAwareLanguageClient.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressInCurrentThread$11(CoreProgressManager.java:557)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:557)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:363)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$0(IndexAwareLanguageClient.java:73)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$1(IndexAwareLanguageClient.java:87)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### PR DESCRIPTION
**Pull request by adietish**
fixes #801

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java [hunk 1]
```diff
@@ -178,6 +185,34 @@ public static String getOptionalTypeParameter(String typeName) {
         return typeName.substring(start + 1, end);
     }
 
+    /**
+     * Returns the first type parameter for the given <code>psiType</code>.
+     * Returns the given <code>psiType</code> if the given psiType has no generic type parameter.
+     *
+     * @param psiType the psiType to return the generic type parameter for
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:192]: Could you add a sample  in the javadoc code like given java.util.Optinal<String> this method will return String.

**Comment by angelozerr** [comment]
It would be nice to add a test with java.util.OptionalInt by adding à java class in à test project and test the expected quarkus property

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java [hunk 2]
```diff
@@ -178,6 +185,34 @@ public static String getOptionalTypeParameter(String typeName) {
...
+     * @return the generic type parameter for the given psiType
+     */
+    public static PsiType getTypeParameter(PsiType psiType) {
+        PsiType type = psiType;
```
Comment (adietish) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:196]: @angelozerr unsure of this default: if the given type has no generic parameter (ex. OptionalInt) I return the type as is.

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java (hunk 1 above)
Comment (adietish) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:192]: What about the impl, you did the original. Does it match the expected?

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java (hunk 2 above)
Comment (adietish) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:196]: @angelozerr would love to get your feedback on this since you did the original.

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java [hunk 3]
```diff
@@ -154,7 +161,7 @@ public static boolean isBinary(PsiModifierListOwner psiMember) {
     }
 
     public static boolean isOptional(String fieldTypeName) {
-        return fieldTypeName.startsWith("java.util.Optional");
+        return fieldTypeName.startsWith("java.util.Optional<");
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:164]: This method is used for another code, I think it should be better to have a new method like `isOptionalWithTypeParameter`

**Comment by angelozerr** [comment]
I have tested quickly your PR with the project https://github.com/quarkusio/registry.quarkus.io:, and I have a `java.lang.StackOverflowError`

```
java.lang.StackOverflowError
	at com.intellij.util.containers.hash.HashUtil.hash(HashUtil.java:24)
	at com.intellij.util.containers.hash.LinkedHashMap.get(LinkedHashMap.java:88)
	at com.intellij.util.containers.SLRUMap.get(SLRUMap.java:80)
	at com.intellij.util.containers.SLRUCache.get(SLRUCache.java:42)
	at com.intellij.util.indexing.impl.MapIndexStorage.lambda$read$1(MapIndexStorage.java:279)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:229)
	at com.intellij.util.indexing.impl.MapIndexStorage.read(MapIndexStorage.java:277)
	at com.intellij.util.indexing.impl.MapIndexStorage.read(MapIndexStorage.java:36)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.read(TransientChangesIndexStorage.java:200)
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java:214)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$getContainingIds$8(StubIndexImpl.java:476)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:229)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$getContainingIds$9(StubIndexImpl.java:475)
	at com.intellij.util.indexing.FileBasedIndexImpl.disableUpToDateCheckIn(FileBasedIndexImpl.java:652)
	at com.intellij.psi.stubs.StubIndexImpl.lambda$getContainingIds$10(StubIndexImpl.java:475)
	at com.intellij.util.indexing.IndexAccessValidator.validate(IndexAccessValidator.java:33)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:472)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:296)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:105)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:93)
	at org.jetbrains.plugins.groovy.lang.stubs.GroovyShortNamesCache.getScriptClassesByFQName(GroovyShortNamesCache.java:54)
	at org.jetbrains.plugins.groovy.lang.stubs.GroovyShortNamesCache.getClassesByFQName(GroovyShortNamesCache.java:83)
	at org.jetbrains.plugins.groovy.lang.psi.impl.javaView.GroovyClassFinder.findClass(GroovyClassFinder.java:48)
	at org.jetbrains.plugins.groovy.lang.psi.impl.javaView.GroovyLightInnerClassFinder.findClass(GroovyLightInnerClassFinder.kt:19)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:89)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:67)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.utils.PsiTypeUtils.findType(PsiTypeUtils.java:147)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:157)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:216)

```

**Comment by adietish** [comment]
@angelozerr unit tests are now green. there's no stack-overflow in registry.quarkus.io any more. Please re-review.

**Comment by adietish** [comment]
@angelozerr `QuarkusConfigMappingProvider#populateConfigObject` is very fragile. Imho the method is far too long and therefore the scope of local variables is far too wide. At some point we should refactor this and split it up into smaller, independent chunks.

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/AbstractPropertiesProvider.java [hunk 4]
```diff
@@ -159,33 +159,31 @@ protected ItemMetadata addItemMetadata(IPropertiesCollector collector, String na
 	 * @return the hint name.
 	 */
 	protected String updateHint(IPropertiesCollector collector, PsiClass type) {
-		if (type == null) {
+		if (type == null
+				|| !type.isEnum()) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/AbstractPropertiesProvider.java:163]: I understand that the code is better, but it looks like it is not releated with the fix, right?

Comment (adietish) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/AbstractPropertiesProvider.java:163]: @angelozerr this line is related to the changes further down. it is not strictly necessary though. I can remove it if you want this to be the bare minimum required for a fix.

File: src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java [hunk 5]
```diff
@@ -145,19 +146,20 @@ private void populateConfigObject(PsiClass configMappingType, String prefixStr,
 				PsiType psiType = method.getReturnType();
 				String returnTypeSignature = getResolvedResultTypeName(method);
 				String resolvedTypeSignature = getRawResolvedTypeName(method);
-				if (isOptional(resolvedTypeSignature)) {
+				if (isGenericOptional(psiType)) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java:149]: isGenericOptional call getTypeParameter and getTypeParameter is called again in the if.

I will keep the isOptional method (remove isGenericOptional method, and after that i will use  getTypeParameter

``` java
if (isOptional(resolvedTypeSignature)) {
 // Here we are in the case:
  // - java.util.Optional<String>
  // - java.util.OptionalInt
  PsiType psiTypeParameter = getTypeParameter(psiType);
  if (psiTypeParameter  != null) {
    // java.util.Optional<String>
    psiType = psiTypeParameter ; 
   resolvedTypeSignature = getRawResolvedTypeName(psiType);
   }

```

File: src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java [hunk 6]
```diff
@@ -201,6 +202,8 @@ private void populateConfigObject(PsiClass configMappingType, String prefixStr,
 						resolvedTypeSignature = getRawResolvedTypeName(((PsiClassType) psiType).getParameters()[0]);
 						returnType = findType(method.getManager(), resolvedTypeSignature);
 						simpleType = isSimpleType(resolvedTypeSignature, returnType);
+					} else if (isInJavaPackage(returnType)) {
+						simpleType = true;
```
Comment (angelozerr) [inline src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java:206]: Could you explain which isecase you are trying to cover? java.utl.List is not a sipleType if I remember.

Comment (adietish) [reply src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java:206]: `java.util.List ` is a collection and is thus catched by the first check. This is needed so that `OptionalInt`, `OptionalLong` etc. wont make it into the recursion at line 217

Comment (adietish) [reply src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java]: changed it, the recursion is now avoided for simple types and types in the java package.

**Comment by adietish** [comment]
@angelozerr corrected what we discussed. Please re-review

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/AbstractPropertiesProvider.java (hunk 4 above)
Comment (adietish) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/AbstractPropertiesProvider.java:163]: @angelozerr moved this refactoring to a separate commit

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java [hunk 7]
```diff
@@ -178,6 +205,43 @@ public static String getOptionalTypeParameter(String typeName) {
...
+     * Examples:
+     * <ul>.
+     *  <li>returns {@code String} for {@code List<String>}</li>
+     *  <li>returns {@code List<String>} for {@code Optional<List<String>>}</li>
+     * </ul>
+     *
+     * @param psiType the psiType to return the generic type parameter for
+     * @return the generic type parameter for the given psiType
+     */
+    public static PsiType getTypeParameter(PsiType psiType) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:221]: I will rename getTypeParameter to getFirstTypeParameter.

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:221]: I will return null instead of the given PsiType because in your code you check getTypeParameter != null

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java [hunk 8]
```diff
@@ -178,6 +205,43 @@ public static String getOptionalTypeParameter(String typeName) {
...
+        PsiClass resolvedClassType = classType.resolve();
+        if (resolvedClassType != null) {
+            PsiTypeParameter[] types = resolvedClassType.getTypeParameters();
+            if (types.length > 0) {
+                PsiClassType.ClassResolveResult resolved = PsiUtil.resolveGenericsClassInType(psiType);
+                Map<PsiTypeParameter, PsiType> substitutions = resolved.getSubstitutor().getSubstitutionMap();
+                type = substitutions.get(types[0]);
+            }
+        }
+        return type;
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:233]: return null;

File: src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java [hunk 9]
```diff
@@ -178,6 +205,43 @@ public static String getOptionalTypeParameter(String typeName) {
...
+    public static PsiType getTypeParameter(PsiType psiType) {
+        PsiType type = psiType;
+        PsiClassType classType = getPsiClassType(psiType);
+        PsiClass resolvedClassType = classType.resolve();
+        if (resolvedClassType != null) {
+            PsiTypeParameter[] types = resolvedClassType.getTypeParameters();
+            if (types.length > 0) {
+                PsiClassType.ClassResolveResult resolved = PsiUtil.resolveGenericsClassInType(psiType);
+                Map<PsiTypeParameter, PsiType> substitutions = resolved.getSubstitutor().getSubstitutionMap();
+                type = substitutions.get(types[0]);
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/utils/PsiTypeUtils.java:230]: return substitutions.get(types[0]);

File: src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java [hunk 10]
```diff
@@ -145,19 +146,23 @@ private void populateConfigObject(PsiClass configMappingType, String prefixStr,
...
-					resolvedTypeSignature = getRawResolvedTypeName(((PsiClassType) psiType).getParameters()[0]);
-					psiType = ((PsiClassType) psiType).getParameters()[0];
+					psiType = getTypeParameter(psiType);
+					if (psiType != null) {
+						resolvedTypeSignature = getRawResolvedTypeName(psiType);
+					}
 				}
 
 				PsiClass returnType = findType(method.getManager(), resolvedTypeSignature);
 				boolean simpleType = isSimpleType(resolvedTypeSignature, returnType);
```
Comment (angelozerr) [inline src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java:160]: isSimpleType should return true for java.util.OptionInt and other java.util.Option* (Long, etc)

File: src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java [hunk 11]
```diff
@@ -145,19 +146,23 @@ private void populateConfigObject(PsiClass configMappingType, String prefixStr,
...
+
 				if (!simpleType) {
-					if (returnType != null && !returnType.isInterface()) {
+					if (returnType != null
+							&& !returnType.isInterface()
+							&& !isInJavaPackage(returnType)) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java:165]: Please remove isInJavaPackage I find it is not clear, You said me that tests fails if you modify isSimpleType with java.util.OptionalInt, could you tell me which test is failing?

**Comment by angelozerr** [comment]
It works like a charm, good job @adietish !
