### PR TITLE
fix: properly wrap QuteSupportForTemplate.getJavadoc in Application.runReadAction()

### LINKED ISSUE #951: "Read access is allowed from inside read-action" when calling QuteSupportForTemplate.getJavadoc
Saw this exception while hovering over a variable's field in a qute template, but I was not able to reproduce it so far: 

```
Details: Current thread: Thread[JobScheduler FJ pool 5/11,4,main] 1850294313
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1004844457

java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1048)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getUncommittedDocuments(PsiDocumentManagerBase.java:832)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexUnsavedDocuments(FileBasedIndexImpl.java:972)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:814)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:352)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:159)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:99)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:87)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:34)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:84)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:107)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:40)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:91)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:69)
	at com.redhat.devtools.intellij.qute.psi.utils.PsiTypeUtils.findType(PsiTypeUtils.java:194)
	at com.redhat.devtools.intellij.qute.psi.QuteSupportForTemplate.getTypeFromParams(QuteSupportForTemplate.java:472)
	at com.redhat.devtools.intellij.qute.psi.QuteSupportForTemplate.getJavadoc(QuteSupportForTemplate.java:371)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$getJavadoc$18(QuteLanguageClient.java:183)
	at com.redhat.devtools.intellij.lsp4ij.IndexAwareLanguageClient.runTask(IndexAwareLanguageClient.java:60)
	at com.redhat.devtools.intellij.lsp4ij.IndexAwareLanguageClient$1.run(IndexAwareLanguageClient.java:39)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressInCurrentThread$10(CoreProgressManager.java:561)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:561)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:381)
	at com.redhat.devtools.intellij.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$0(IndexAwareLanguageClient.java:36)
	at com.redhat.devtools.intellij.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$1(IndexAwareLanguageClient.java:50)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### PR DESCRIPTION
**Pull request by fbricon**
Fixes #951

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java [hunk 1]
```diff
@@ -366,16 +366,16 @@ public String getJavadoc(QuteJavadocParams params, IPsiUtils utils, ProgressIndi
...
 			}
 
-			utils = utils.refine(javaProject);
-
-			PsiClass type = getTypeFromParams(params.getSourceType(), params.getProjectUri(), javaProject, monitor);
-			if (type == null) {
-				return null;
-			}
-			final var finalUtils = utils;
+			final var refinedUtils = utils.refine(javaProject);;
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/intellij/qute/psi/QuteSupportForTemplate.java:369]: remove the duplicate `;`

**Comment by angelozerr** [comment]
Thanks @fbricon !
