### PR TITLE
fix: Quarkus Dev Mode is having trouble running main module by using Gradle with Kotlin DSL

### LINKED ISSUE #1374: Quarkus Dev Mode is having trouble running main module by using `Gradle with Kotlin DSL`
Hi team,

After upgrading to plugin 2.0.0, the dev mode launcher seems to have issue running the main module, please see attached screenshot:
Screenshot 2024-08-28 at 9 36 13 AM

This is a fresh kotlin project generated by quarkus cli.

Old projects also suffered from the same.

Thanks,
Charles

### PR DESCRIPTION
**Pull request by angelozerr**
fix: Quarkus Dev Mode is having trouble running main module by using Gradle with Kotlin DSL

Fixes #1374

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java [hunk 1]
```diff
@@ -152,6 +150,34 @@ private static boolean isQuarkusModule(VirtualFile file, Project project) {
     }
 
     public static @Nullable VirtualFile getModuleDirPath(@NotNull Module module) {
-        return LocalFileSystem.getInstance().findFileByPath(ModuleUtilCore.getModuleDirPath(module));
+        VirtualFile[] roots = getContentRoots(module);
+        if (roots.length > 0) {
+            return roots[0];
+        }
+        return VfsUtil.findFileByIoFile(new File(ModuleUtilCore.getModuleDirPath(module)), true);
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java:157]: return ProjectUtil.guessModuleDir(module);

File: src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java [hunk 2]
```diff
@@ -104,7 +103,7 @@ private static String getTemplateBaseDir(Module javaProject) {
     public static @Nullable VirtualFile findBestResourcesDir(@NotNull Module javaProject) {
         List<VirtualFile> resourcesDirs = ModuleRootManager.getInstance(javaProject).getSourceRoots(JavaResourceRootType.RESOURCE);
         if (!resourcesDirs.isEmpty()) {
-            Collections.sort(resourcesDirs, ROOT_COMPARATOR); // put root with smallest path first (eliminates generated sources roots)
+            QuarkusModuleUtil.sortRoot(resourcesDirs); // put root with smallest path first (eliminates generated sources roots)
             // The module configure 'Resources folder'
             // 1) loop for each configured resources dir and returns the first which contains 'templates' folder.
             for (var dir : resourcesDirs) {
```
Comment (fbricon) [inline src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java:109]: L118 to L122 can be removed, it's already covered by QuarkusModuleUtil.getModuleDirPath

**Comment by angelozerr** [comment]
@hjbolide could you please install the zip that you can download at 

https://github.com/redhat-developer/intellij-quarkus/actions/runs/10594555424

on the bottom of the page:

image

and tell me if it fixes your issue.

Thanks!

File: src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java (hunk 1 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java:157]: Are you sure? Need to debug that to check if we have the same result.

File: src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java (hunk 2 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/qute/psi/utils/PsiQuteProjectUtils.java:109]: Good cach! I wanted to do that, but I forget it while my refactoring :)

fixed.

File: src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java (hunk 1 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java:157]: But this code is just a fallback, because generally project have contents root.

Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java:157]: no I thought ModuleUtilCore.getModuleDirPath was internal. But it looks fine to use

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java:157]: I would prefer using VfsUtil.findFileByIoFile(new File(ModuleUtilCore.getModuleDirPath(module)), true); which have the same behavior than previous version.

Are you OK with that or do you prefer I use ProjectUtil.guessDir

Comment (fbricon) [reply src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java:157]: yes I said it's fine to use

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusModuleUtil.java:157]: > no I thought ModuleUtilCore.getModuleDirPath was internal. But it looks fine to use

It is `module.getModuleFilePath()` which is internal and ModuleUtilCore.getModuleDirPath use it.
